name: dbt-learn-ppd

version: "1.0.0"

profile: snowflake

analysis-paths: ["analysis"]
data-paths: ["assets"]
test-paths: ["tests"]
macro-paths: ["custom_macros"]
snapshot-paths: ["archives"]
docs-paths: ["docs"]

target-path: "compiled"
log-path: dbt_logs
modules-path: packages

clean-targets: [target, dbt_modules, logs]

query-comment: string

require-dbt-version: version-range | [version-range]

quoting:
  database: true | false
  schema: true | false
  identifier: true | false

models:
  <model-configs>

seeds:
  <seed-configs>

snapshots:
  <snapshot-configs>

on-run-start: sql-statement | [sql-statement]
on-run-end: sql-statement | [sql-statement]